aws_region              = "us-east-1"
environment             = "dev"
vpc_cidr                = "10.0.0.0/16"
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs    = ["10.0.10.0/24", "10.0.11.0/24"]
instance_type           = "t3.micro"
instance_count          = 1
db_instance_class       = "db.t3.micro"
db_allocated_storage    = 20
db_name                 = "queensappdb"
db_username             = "admin"
db_password             = "DevPassword123!"
