aws_region              = "us-east-1"
environment             = "prod"
vpc_cidr                = "10.2.0.0/16"
public_subnet_cidrs     = ["10.2.1.0/24", "10.2.2.0/24"]
private_subnet_cidrs    = ["10.2.10.0/24", "10.2.11.0/24"]
instance_type           = "t3.medium"
instance_count          = 2
db_instance_class       = "db.t3.medium"
db_allocated_storage    = 100
db_name                 = "queensappdb"
db_username             = "admin"
db_password             = "ProdPassword123!"
