aws_region              = "us-east-1"
environment             = "staging"
vpc_cidr                = "10.1.0.0/16"
public_subnet_cidrs     = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnet_cidrs    = ["10.1.10.0/24", "10.1.11.0/24"]
instance_type           = "t3.small"
instance_count          = 2
db_instance_class       = "db.t3.small"
db_allocated_storage    = 50
db_name                 = "queensappdb"
db_username             = "admin"
db_password             = "StagingPassword123!"
